declare namespace Enums {
  enum EventTypesEnum {
    JOINED = 'JOINED',
    LEFT = 'LEFT',
    USER_RAISED_HAND = 'USER_RAISED_HAND',
    USER_REMOVE_UPCOMING_CONVERSATION = 'USER_REMOVE_UPCOMING_CONVERSATION',
    USER_ADD_UPCOMING_CONVERSATION = 'USER_ADD_UPCOMING_CONVERSATION',
    USER_ADD_SPEAKER_CONVERSATION = 'USER_ADD_SPEAKER_CONVERSATION',
    USER_CHANGE_STATUS = 'USER_CHANGE_STATUS',
  }

  interface IEventTypes {
    constants: EventTypesEnum;
  }
}
