declare namespace Enums {
  enum EventTypes {
    JOINED = 0,
    LEFT = 1,
    USER_RAISED_HAND = 2,
    USER_REMOVE_UPCOMING_CONVERSATION = 3,
    USER_ADD_UPCOMING_CONVERSATION = 4,
    USER_ADD_SPEAKER_CONVERSATION = 5,
    USER_CHANGE_STATUS = 6,
  }
}
