declare namespace EventTypes {
  const JOINED: 'JOINED';
  const LEFT: 'LEFT';
  const USER_RAISED_HAND: 'USER_RAISED_HAND';
  const USER_REMOVE_UPCOMING_CONVERSATION: 'USER_REMOVE_UPCOMING_CONVERSATION';
  const USER_ADD_UPCOMING_CONVERSATION: 'USER_ADD_UPCOMING_CONVERSATION';
  const USER_ADD_SPEAKER_CONVERSATION: 'USER_ADD_SPEAKER_CONVERSATION';
  const USER_CHANGE_STATUS: 'USER_CHANGE_STATUS';
}
