declare namespace EventDetailTypes {
  const LISTENER_TO_SPEAKER : 'LISTENER_TO_SPEAKER';
  const LISTENER_TO_UPCOMING : 'LISTENER_TO_UPCOMING';
  const UPCOMING_TO_LISTENER : 'UPCOMING_TO_LISTENER';
  const UPCOMING_TO_SPEAKER : 'UPCOMING_TO_SPEAKER';
  const SPEAKER_TO_LISTENER : 'SPEAKER_TO_LISTENER';
  const JOINED : 'JOINED';
  const LEFT : 'LEFT';
}
